Exercise 3 — One-hot encoding from scratch, dimensionality, and the dummy trap.

Create A nominal column with 4 categories, 8 rows.

Implement one-hot encoding manually — no pd.get_dummies, no OneHotEncoder.
Before coding: 
predict how many new columns N categories produces, and what total width you'd get 
with a second categorical column of 7 categories added to the same dataframe.
For any single row, sum across that feature's one-hot columns. Predict what that sum always equals, 
and explain why that creates a linear dependency among the columns.
Trace what happens if you feed all one-hot columns (none dropped) into a linear regression with an 
intercept. Name the problem this causes, how many of the N columns you should actually keep, and why 
dropping one loses zero information.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'Name':['Prabin','Samir','Chadup','Bikesh','Deepesh','Aditi','Alwin','Prajwal'],'Age':[21,23,34,18,21,23,34,22], 'Ed_lvl':['PhD','Bachelors','High School','Masters','High School','Bachelors','Masters','Bachelors'],'fav_color':['blue','green','red','blue','red','green','red','yellow']})
df

      Name  Age       Ed_lvl fav_color
0   Prabin   21          PhD      blue
1    Samir   23    Bachelors     green
2   Chadup   34  High School       red
3   Bikesh   18      Masters      blue
4  Deepesh   21  High School       red
5    Aditi   23    Bachelors     green
6    Alwin   34      Masters       red
7  Prajwal   22    Bachelors    yellow

In [4]:
list(df['fav_color'].value_counts().keys())

['red', 'blue', 'green', 'yellow']

In [5]:
len(df['fav_color'])

8

In [6]:
for itr in df['fav_color'].value_counts().keys():
    print(itr)

red
blue
green
yellow

In [7]:
df['fav_color'].value_counts().keys()

Index(['red', 'blue', 'green', 'yellow'], dtype='object', name='fav_color')

In [8]:
ohe_kols = pd.DataFrame(index=df['fav_color'].index, columns=list(df['fav_color'].value_counts().keys()), dtype=int)
ohe_kols # this shows with out .fillna(0), we have df full of NA's

   red  blue  green  yellow
0  NaN   NaN    NaN     NaN
1  NaN   NaN    NaN     NaN
2  NaN   NaN    NaN     NaN
3  NaN   NaN    NaN     NaN
4  NaN   NaN    NaN     NaN
5  NaN   NaN    NaN     NaN
6  NaN   NaN    NaN     NaN
7  NaN   NaN    NaN     NaN

In [9]:
ohe_kols = pd.DataFrame(index=df['fav_color'].index, columns=list(df['fav_color'].value_counts().keys()), dtype=int).fillna(0).astype(int)
ohe_kols.loc[0,'purple'] = 1
ohe_kols # this shows without  'inner if loop',we introduce a new ohe column of the newer category each time we encounter an unknown category but it only changes the dedicated row to 1 and leaving rest of the  values in that newly created column as NaN.

   red  blue  green  yellow  purple
0    0     0      0       0     1.0
1    0     0      0       0     NaN
2    0     0      0       0     NaN
3    0     0      0       0     NaN
4    0     0      0       0     NaN
5    0     0      0       0     NaN
6    0     0      0       0     NaN
7    0     0      0       0     NaN

In [10]:
class onehot_encoder():
    def __init__(self):
        pass
    def encode(self,column):
        self.column = column
        self.unique_values = list(column.value_counts().keys()) # getting the categories of a categorical column as a list
        
        ohe_cols = pd.DataFrame(
                    index=column.index,
                    columns= self.unique_values,
                    dtype = int 
                    ).fillna(0).astype(int)   #  before the inital values of the df was  in float, so to chnage that astype(int) is used here 

        for index,itr in self.column.items(): # this loop is for iterating over all the rows of the column to be encoded
            for unique_value in self.unique_values: 
                # if (itr == unique_value):
                ohe_cols.loc[index,itr] = 1   # this sets the value of matching colum to 1 .
                break
        return ohe_cols

In [11]:
ohe = onehot_encoder()
ohe.encode(df['fav_color'])

   red  blue  green  yellow
0    0     1      0       0
1    0     0      1       0
2    1     0      0       0
3    0     1      0       0
4    1     0      0       0
5    0     0      1       0
6    1     0      0       0
7    0     0      0       1

In [12]:
# df['fav_color'] contains 4 categories. thus in ohe we introduce 4 new columns.

In [16]:
cars = pd.read_csv('cars.csv')
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

# One hot encoding using pandas

In [19]:
cars['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [21]:
# one hot encoding
pd.get_dummies(cars,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1 one hot encoding

In [ ]:
pd.get_dummies(cars,columns=['fuel','owner'],drop_first=True) # the first column of every ohe column is dropped to remove multicollinearity issue.

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## But we generally do our OHE using sklearn onehotencoder class

In [45]:
from numpy import int32
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=int32)
X_train,X_test,y_train,y_test = train_test_split(cars.iloc[:,0:4],cars.iloc[:,-1],test_size=0.2,random_state=42)

In [46]:
X_train_transformed = ohe.fit_transform(X_train[['fuel','owner']])
X_test_transformed = ohe.transform(X_test[['fuel','owner']])

In [47]:
X_train_transformed

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int32)

In [61]:
np.hstack((X_train[['brand','km_driven']].values,X_train_transformed))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

## OHE using most frequent variables.

In [72]:
print(cars['brand'].nunique())
cars['brand'].value_counts()

32

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [80]:
car_counts = cars['brand'].value_counts()
threshold = 100

In [84]:
minor_cars = car_counts[car_counts <= threshold].index
minor_cars

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [96]:
brand_new_categories = cars['brand'].replace(minor_cars,"uncommon")
# brand_new_catgeories.value_counts()
pd.get_dummies(brand_new_categories).astype(int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5984,0,0,0,0,0,0,1,0,0,0,0,0,0
8089,0,0,0,0,0,0,0,0,0,1,0,0,0
4498,0,0,1,0,0,0,0,0,0,0,0,0,0
4858,0,0,0,1,0,0,0,0,0,0,0,0,0
438,0,0,0,0,0,0,1,0,0,0,0,0,0