### this notebook is intended as a playground for understanding and experimentation regarding encoding of catergorical variables.
    the current module includes work on Label and Ordinal encoding.

Exercise 1
<ul>Label encoding and fabricated distance</ul>
<ul>Take a small dataset (5–6 rows) with a nominal color column: red, blue, green (repeats fine).</ul>

<ul>Build a manual label encoder — your own dict mapping, not pandas.factorize or sklearn.</ul>
<ul>Before running anything: using your encoded integers, hand-compute the Euclidean distance bw a red row & a </ul><ul>blue row, and between a red row and a green row. Predict which pair your encoding treats as "closer."</ul>
<ul>Now reassign the integer codes in a different arbitrary order (swap which color gets 0/1/2) and recompute your </ul><ul>predicted distances.</ul>
<ul>Answer: did the "closeness" relationship change just because you relabeled? What does that tell you about handing </ul><ul>label-encoded nominal data to anything that computes distance?</ul>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.DataFrame({'Name':['Prabin','Samir','Chadup','Bikesh'],'Age':[21,23,34,18], 'fav_color':['blue','green','red','blue']})
df

     Name  Age fav_color
0  Prabin   21      blue
1   Samir   23     green
2  Chadup   34       red
3  Bikesh   18      blue

In [3]:
# could have implemented the test df at once , but wanted to revise and brush small concepts along the way. so concat was used.
new_df = pd.DataFrame({'Name':['Deepesh','Aditi','Alwin'],'Age':[19,23,28],'fav_color':['blue','green','red']})
new_df

      Name  Age fav_color
0  Deepesh   19      blue
1    Aditi   23     green
2    Alwin   28       red

In [4]:
df = pd.concat([df,new_df],ignore_index = True)
df

      Name  Age fav_color
0   Prabin   21      blue
1    Samir   23     green
2   Chadup   34       red
3   Bikesh   18      blue
4  Deepesh   19      blue
5    Aditi   23     green
6    Alwin   28       red

In [5]:
# checking if i can iterate over a series
for itr in df['fav_color'].keys():
    print(itr)

0
1
2
3
4
5
6

In [6]:
# encoding logic for round 1
encode_1 = {'blue':3,'red':2,'green':1,'NA':0}
encode_1.values()

dict_values([3, 2, 1, 0])

In [7]:
class labelencoder:
    def __init__(self,encoding = {}):
        self.encoding = encoding
    def encode_color(self,column):
        self.column = column
        self.encoded_column = []
        for itr in self.column.values:
            if(itr in self.encoding.keys()):
                itr = self.encoding[itr]
            else:
                # for unknown values in color column
                itr = self.encoding['NA']
            self.encoded_column.append(itr)
        return pd.DataFrame(self.encoded_column) # here i am changing back the list to a dataframe

In [8]:
# Round 1
le1 = labelencoder(encode_1)
r1_encoded = le1.encode_color(df['fav_color'])
df['fav_color_encoded_r1'] = r1_encoded # here i am adding a new  only  column 'fav_color_encoded_r1' with encoded values
df

      Name  Age fav_color  fav_color_encoded_r1
0   Prabin   21      blue                     3
1    Samir   23     green                     1
2   Chadup   34       red                     2
3   Bikesh   18      blue                     3
4  Deepesh   19      blue                     3
5    Aditi   23     green                     1
6    Alwin   28       red                     2

In [ ]:
# Round 1 
# The ecludian distance between scalars is absolute
# #of the difference bw 2 values
# Ecludian distance between:
#     1.Blue and Green = abs(3 - 1) = 2
#     2.Blue and Red = abs(3 - 2) = 1

In [ ]:
# first round of my manual label encoding  is treating (blue and red) as closer.
# and (blue and green) are far from each other.

In [10]:
# reassigning the encoding of colors with different arbitary integers.
encode_2 = {'blue':1,'red':3,'green':2}

le2 = labelencoder(encode_2)
r2_encoded = le2.encode_color(df['fav_color'])
df['fav_color_encoded_r2'] = r2_encoded # here i am replacing only the values of column 'fav_color' with encoded values
df

      Name  Age fav_color  fav_color_encoded_r1  fav_color_encoded_r2
0   Prabin   21      blue                     3                     1
1    Samir   23     green                     1                     2
2   Chadup   34       red                     2                     3
3   Bikesh   18      blue                     3                     1
4  Deepesh   19      blue                     3                     1
5    Aditi   23     green                     1                     2
6    Alwin   28       red                     2                     3

In [ ]:
# Round 2 
# Ecludian distance between:
#     1.Blue and Green = abs(1 - 2) = 1
#     2.Blue and Red = abs(1 - 3) = 2


# second round of my manual label encoding  is treating (blue and green) as closer.
# and (blue and red) are far from each other.



# the answer to which colors are closer changes with how we choose to encode
# catgorical varibles and depend upon the values we assign to them during encoding logic.