### this notebook is intended as a playground for understanding and experimentation regarding encoding of catergorical variables.
    the current module includes work on Label and Ordinal encoding.

Exercise 1
<ul>Label encoding and fabricated distance</ul>
<ul>Take a small dataset (5–6 rows) with a nominal color column: red, blue, green (repeats fine).</ul>

<ul>Build a manual label encoder — your own dict mapping, not pandas.factorize or sklearn.</ul>
<ul>Before running anything: using your encoded integers, hand-compute the Euclidean distance bw a red row & a </ul><ul>blue row, and between a red row and a green row. Predict which pair your encoding treats as "closer."</ul>
<ul>Now reassign the integer codes in a different arbitrary order (swap which color gets 0/1/2) and recompute your </ul><ul>predicted distances.</ul>
<ul>Answer: did the "closeness" relationship change just because you relabeled? What does that tell you about handing </ul><ul>label-encoded nominal data to anything that computes distance?</ul>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.DataFrame({'Name':['Prabin','Samir','Chadup','Bikesh'],'Age':[21,23,34,18], 'fav_color':['blue','green','red','blue']})
df

     Name  Age fav_color
0  Prabin   21      blue
1   Samir   23     green
2  Chadup   34       red
3  Bikesh   18      blue

In [3]:
new_df = pd.DataFrame({'Name':['Deepesh','Aditi','Alwin'],'Age':[19,23,28],'fav_color':['blue','green','red']})
new_df

      Name  Age fav_color
0  Deepesh   19      blue
1    Aditi   23     green
2    Alwin   28       red

In [4]:
df = pd.concat([df,new_df],ignore_index = True)
df['fav_color'].value_counts()
df

      Name  Age fav_color
0   Prabin   21      blue
1    Samir   23     green
2   Chadup   34       red
3   Bikesh   18      blue
4  Deepesh   19      blue
5    Aditi   23     green
6    Alwin   28       red