# this notebook includes work on date and time columns and ways to handle them.

In [1]:
import numpy as np
import pandas as pd

In [4]:
date_df = pd.read_csv('orders.csv')
time_df = pd.read_csv('messages.csv')

In [5]:
date_df.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time_df.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date_df.info() # mostly the date column is present as str object,we need to change type to unlock batter analysis of date and time column.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [13]:
time_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

# Working with Dates

In [14]:
# Converting to datetime datatype
date_df['date'] = pd.to_datetime(date_df['date'])

In [15]:
date_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

#### 1. Extract year

In [21]:
date_df['date_year'] = date_df['date'].dt.year

date_df.sample(5)

          date  product_id  city_id  orders  date_year
436 2019-10-11         983       25      45       2019
654 2019-04-22          14        2       1       2019
848 2019-07-11        3524       25      99       2019
247 2019-12-06        7148       16      29       2019
456 2018-12-04        1622        9       4       2018

#### 2. Extract Month

In [22]:
date_df['date_month_no'] = date_df['date'].dt.month

date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [25]:
date_df['date_month_name'] = date_df['date'].dt.month_name()

date_df.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### Extract Days

In [26]:
date_df['date_day'] = date_df['date'].dt.day

date_df.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [27]:
# day of week
date_df['date_dow'] = date_df['date'].dt.dayofweek

date_df.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [29]:
# day of week - name

date_df['date_dow_name'] = date_df['date'].dt.day_name()

date_df.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [31]:
# is weekend?

date_df['date_is_weekend'] = np.where(date_df['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date_df.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### Extract week of the year

In [36]:
date_df['date_week'] = date_df['date'].dt.isocalendar().week

date_df.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

#### Extract Quarter

In [37]:
date_df['quarter'] = date_df['date'].dt.quarter

date_df.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

#### Extract Semester

In [39]:
date_df['semester'] = np.where(date_df['quarter'].isin([1,2]), 1, 2)

date_df.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

#### Extract Time elapsed between dates

In [40]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 28, 22, 59, 22, 348028)

In [41]:
today - date_df['date']

0     2484 days 22:59:22.348028
1     2966 days 22:59:22.348028
2     2897 days 22:59:22.348028
3     2599 days 22:59:22.348028
4     2822 days 22:59:22.348028
                 ...
995   2912 days 22:59:22.348028
996   2853 days 22:59:22.348028
997   2701 days 22:59:22.348028
998   2766 days 22:59:22.348028
999   2540 days 22:59:22.348028
Name: date, Length: 1000, dtype: timedelta64[us]

In [43]:
(today - date_df['date']).dt.days

0      2484
1      2966
2      2897
3      2599
4      2822
       ...
995    2912
996    2853
997    2701
998    2766
999    2540
Name: date, Length: 1000, dtype: int64

In [47]:
# Months passed
date_df['date'].dt.to_period('M') - pd.Timestamp.today().to_period('M')

0      <-81 * MonthEnds>
1      <-97 * MonthEnds>
2      <-95 * MonthEnds>
3      <-85 * MonthEnds>
4      <-92 * MonthEnds>
             ...
995    <-95 * MonthEnds>
996    <-93 * MonthEnds>
997    <-88 * MonthEnds>
998    <-90 * MonthEnds>
999    <-83 * MonthEnds>
Name: date, Length: 1000, dtype: object

In [49]:
time_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [50]:
# Converting to datetime datatype
time_df['date'] = pd.to_datetime(time_df['date'])

In [51]:
time_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [52]:
time_df['hour'] = time_df['date'].dt.hour
time_df['min'] = time_df['date'].dt.minute
time_df['sec'] = time_df['date'].dt.second

time_df.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### Extract Time part

In [53]:
time_df['time'] = time_df['date'].dt.time

time_df.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### Time difference

In [54]:
today - time_df['date']

0     4670 days 22:09:22.348028
1     4534 days 23:19:22.348028
2     5020 days 22:38:22.348028
3     4322 days 22:28:22.348028
4     4719 days 23:48:22.348028
                 ...
995   5309 days 22:09:22.348028
996   4630 days 23:45:22.348028
997   5095 days 23:22:22.348028
998   5211 days 23:25:22.348028
999   4483 days 23:34:22.348028
Name: date, Length: 1000, dtype: timedelta64[us]

In [57]:
# in seconds

(today - time_df['date'])/np.timedelta64(1,'s')

0      4.035678e+08
1      3.918216e+08
2      4.338095e+08
3      3.735017e+08
4      4.078073e+08
           ...
995    4.587774e+08
996    4.001175e+08
997    4.402921e+08
998    4.503147e+08
999    3.874161e+08
Name: date, Length: 1000, dtype: float64

In [58]:
# in minutes

(today - time_df['date'])/np.timedelta64(1,'m')

0      6.726129e+06
1      6.530359e+06
2      7.230158e+06
3      6.225028e+06
4      6.796788e+06
           ...
995    7.646289e+06
996    6.668625e+06
997    7.338202e+06
998    7.505245e+06
999    6.456934e+06
Name: date, Length: 1000, dtype: float64

In [59]:
# in hours

(today - time_df['date'])/np.timedelta64(1,'h')

0      112102.156208
1      108839.322874
2      120502.639541
3      103750.472874
4      113279.806208
           ...
995    127438.156208
996    111143.756208
997    122303.372874
998    125087.422874
999    107615.572874
Name: date, Length: 1000, dtype: float64